### ISSUE TITLE
Should you not place a message on the old repo to let users know what happened?

### ISSUE THREAD

**Issue by embluk** [apilayer/freegeoip#12]
Just thought it might make sense to explain the situation for a little while, as everyone converts over?

Also the site at freegroip still has references to the old project, such as the direct contact link and git hub link...

**Comment by fiorix** [comment]
The site is definitely the highest priority here.

**Comment by julian-zehetmayr** [comment]
Hi Guys, 

Here's our announcement: https://github.com/apilayer/freegeoip/

**Comment by embluk** [comment]
I guess we can close this issue now then :)
