### ISSUE TITLE
free geoip legacy request

### ISSUE THREAD

**Issue by marcus-at-localhost** [apilayer/freegeoip#16]
I was able to just call https://freegeoip.net/json/ to get the ip address (+location) now I have to add the ip manually. Why is that?

**Comment by ipipdotnet** [comment]
@marcus-at-localhorst  see https://www.ip.la  A Simple Public IP Address And IP Geo Location API

**Comment by kelliekel** [comment]
@marcus-at-localhorst Try this:
`http://api.ipstack.com/check?access_key=<YOUR_ACCESS_KEY>`

**Comment by OlagStegan** [comment]
The problem many are potentially finding IS:
this has gone from being true open source program supported by community @Github to being yet another commercial clone. Albeit with a restricted "f(r)ee" element.

For those that have integrated the code into their sites/apps this all becomes rather distasteful.

For the one off surfer - well you take your choice, plenty out there to choose from with more advertizing here on Github to follow and to irritate the rest of us!
