### ISSUE TITLE
Why is respons data less correct then before?

### ISSUE THREAD

**Issue by HCSier** [apilayer/freegeoip#17]
In the old https://freegeoip.net/json the returned city was (and is on this very moment)  exactly right, but now (on same IP-address) the ipstack engine returns a completely wrong city, lng, lat.
So moving to the new and improved api, the accuracy dropped?

**Comment by julian-zehetmayr** [comment]
Hi!

Can you give us an example IP where you are seeing such discrepancies?

Many Thanks!

**Comment by Schusti91** [comment]
Closed due to inactivity.

Contact support@ipstack.com if further assistance is needed.
