### ISSUE TITLE
DELETE/ANONYMIZE endpoint for looked up IPs

### ISSUE THREAD

**Issue by danielalmeidagoncalves** [apilayer/freegeoip#18]
Do you have (or plan to have) any kind of endpoint that someone could triggered to delete/anonymize a looked up IP? Within the GDPR process we need to make sure that all the data that we deliver to as they call "third-party processor" need also to be GDPR compliant.

**Comment by OlagStegan** [comment]
You will need to delete all your entries in your server logs and in the logs of your hosting co as well as well as any node on the web. You have access to those as well?
World Domination Europe especially has gone totally MAD with this crappy bit of dumb ass legislation.
Anyway use the opt-out "required for legal purposes" ie when some gov. agency sends you a subpoena.

**Comment by danielalmeidagoncalves** [comment]
@OlagStegan This is something that I agree with you, and even more if we are talking about those who develop software like us. But I am afraid that it does not work that way. Don't know how would be the appreciation of such entities that would regulate the law but we have to protect ourselves from those, and act in every request to be forgotten, even on logs that we barely have access.

**Comment by OlagStegan** [comment]
Yo Europeans have to figure that one out. I guess here in the US any attempt to delete logs might get a swift response from NSA.
Don't get me wrong I'm fine with making visitors aware of what information is collected on servers we have full control of and the apps on which we write ourselves. But bad laws made by incompetent foreigners with little knowledge of how the global internet actually works? I'll not be losing any sleep over.

**Comment by Schusti91** [comment]
Hi @danielalmeidagoncalves 

The official freegeoip successor ipstack.com is GDPR compliant and we also offer a DPA if needed.

From a recent conversation with a customer using freegeoip, we found out that setting the last octet of the IP addresses should also _anonymize_ it.

Please contact support@ipstack.com for further assistance.

Andreas,

**Comment by danielalmeidagoncalves** [comment]
Thanks @Schusti91 for the info :) Probably we will move to ipstack.com
