### ISSUE TITLE
Paying $3503.635 a year to get equivalent of previous free service??? wow

### ISSUE THREAD

**Issue by codeliger** [apilayer/freegeoip#20]
I was allowed 10,000 requests per hour.
10,000 * 24 * (365 / 12) = 7,300,000 requests per month allowed
Now I am allowed 10,000 requests per month?
959.90 / 2,000,000 * 7,300,000 = $3503.635 per year to get the same service i was provided before??? WHAT

**Comment by OlagStegan** [comment]
Geesh! We are still running free with original code from free service. Having downloaded it. Now training up coder in GOlang to provide support plus future. As original repro no longer supported and very opposed to  new pay for use of opensource policy. Especially when Git repro just used to advertise their product!
Advice: take copy, get someone to install docker and run yourself just like old days but a little more complex. Cost = lot less than that /month

**Comment by MatthewAwesome** [comment]
Greed is pervasive...
