### ISSUE TITLE
*

### ISSUE THREAD

**Issue by lucasmontec** [apilayer/freegeoip#25]

**Comment by Yankovsky** [comment]
What have you done to freegeoip!?

**Comment by nathan-fiscaletti** [comment]
![but why](https://media.tenor.com/images/8e044ede50625f5f09f0d36d267eba1b/tenor.gif)

**Comment by lucasmontec** [comment]
someone had access to my computer. Sorry for the issue.
Not that I'm happy with putting a price tag on a free service, haha. But I wouldn't miss use github this way.
